### PR TITLE
(maint) Update to latest clj-parent

### PR DESCRIPTION
**Pull request by Magisus**

### CODE REVIEW

**Comment by Magisus** [comment]
Fwiw this lib doesn't even have jenkins jobs.

**Comment by Magisus** [comment]
This should wait on some of the updates (like jetty and BC) that are going into clj-parent that also show up here when this is scanned.

**Review by mwaggett — APPROVED** [review]

**Comment by Magisus** [comment]
Updated to use clj-parent 4.6.12

**Comment by Magisus** [comment]
Trying to retrigger travis.

**Comment by Magisus** [comment]
We accidentally released jetty with no java 8 support. Will bump this once the new clj-parent is out.

**Comment by Magisus** [comment]
Okay this looks good now.

**Review by mwaggett — APPROVED** [review]

**Pull request merged**
